<a href="https://colab.research.google.com/github/VideoAlligator/object-natural-scenes-detection/blob/dev-Claire/VideoInformationProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[COCO and Pascal VOC data format for object detection](https://towardsdatascience.com/coco-data-format-for-object-detection-a4c5eaf518c5)

[object detection of images](https://www.researchgate.net/publication/312037041_A_review_and_an_approach_for_object_detection_in_images)

[image AI PDF](https://buildmedia.readthedocs.org/media/pdf/imageai/latest/imageai.pdf)

This document is aiming to form an algorithm to process the information and pass on to the web backend part. 

**The below codes are for Video Database Module.**

#### **Main Notes**:

Logic:
1. Get **TMDB ids** from TMDB dataset
2. Use **API key & TMDB ids** to get **YouTube ids** from TMDB API
3. Use YouTube ids to format YouTube links, which will be used by Pafy.

---
Instruction: How to get movie trailer YouTube ids from TMDb API: https://oupton.github.io/startup-ds/. Note:*The TMDB API key can be found in our Code folder*.

TMDB dataset (where we get tmdbid): https://www.kaggle.com/rounakbanik/the-movies-dataset?select=keywords.csv. 

Note: 
1. The dataset consists of movies released on or before July 2017.
2. The dataset has been uploaded to our Code folder.



In [ ]:
import time
import requests
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


#### **Get TMDB ids from the TMDB dataset**

In [ ]:
def read_dataset_csv(fileName):
  file = pd.read_csv(
    "/content/gdrive/MyDrive/Capstone/Code/TMDB/"+fileName,
    usecols = header,
    index_col=False)

  return file

In [ ]:
fileName = 'tmdb_movies_metadata.csv' # can be found in the Code -> TMDB folder 
header = ['genres','homepage','id','original_language','original_title','overview', 'poster_path','release_date', 'runtime', 'title',]#10 columns 
fileList_1 = read_dataset_csv(fileName)
print(fileList_1.shape)

(45466, 10)


In [ ]:
#For test: use the first 100 movies
test_list = fileList_1[:100].to_dict('index')

#### **Get YouTube ids from TMDB API**

In [ ]:
TMDB_API_KEY = 'e0476a281215758d95503294fc0cb530' # can be found in the Code -> TMDB folder 
TMDB_VIDEO_URL = 'https://api.themoviedb.org/3/movie/{}/videos?api_key={}'

Pull the YouTube trailer IDs of the movies using the TMDb API.

Please note that TMDb has a ***40 request per 10 second interval rate limiting***, so be cautious not to upset this.

In [ ]:
def get_youtube_data(video_data):
  trailers = {}
  url_base = 'https://www.youtube.com/watch?v='
  for i,(key, value) in enumerate(video_data.items()):
      try:  
        url = TMDB_VIDEO_URL.format(value['id'], TMDB_API_KEY)
        resp = requests.get(url)
        if resp.status_code != 200:
            print('Error: Failed to retrieve video for TMDb ID {} with status code: {}'\
                    .format(value['id'], resp.status_code))
            trailers.append([])
        else:
            youtube_results = [] #a list of ids
            for video in resp.json()['results']:
              if video['site'] == 'YouTube' and (video['type'] in { 'Teaser', 'Trailer' }) and video['key'] != '':
                  youtube_results.append([video['name'],url_base+video['key']])
            if len(youtube_results) >0:
              temp = {}
              temp['Youtube Info'] = youtube_results
              temp['Video Info'] = value
              trailers[value['id']] = temp

        # Rate limiting, stall 10 seconds
        if i != 0 and i % 40 == 0:
            print('Sleep')
            time.sleep(10)
      except:
        print('Send Request Failed')
  
  return trailers

In [ ]:
test_trailer_list = get_youtube_data(test_list)

Sleep
Sleep


In [ ]:
#Visualize Data
n = 0
for key, value in test_trailer_list.items():
  print('TMDB ID = ',key)
  print('Youtube Info = ',value['Youtube Info'])
  print('Movie Info = ',value['Video Info'])
  print('--------------------------------------------')
  print('--------------------------------------------')
  n+=1
  if (n>3): 
    break


TMDB ID =  862
Youtube Info =  [['Toy Story Teaser Trailer HD Widescreen', 'https://www.youtube.com/watch?v=4j_qfJN0qd4'], ['Toy Story (1995) Trailer #1 | Movieclips Classic Trailers', 'https://www.youtube.com/watch?v=v-PjgYDrg70'], ['Toy Story Trailer 1995 | Disney Throwback | Oh My Disney', 'https://www.youtube.com/watch?v=tN1A2mVnrOM']]
Movie Info =  {'genres': "[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]", 'homepage': 'http://toystory.disney.com/toy-story', 'id': '862', 'original_language': 'en', 'original_title': 'Toy Story', 'overview': "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.", 'poster_path': '/rhIRbceoE9lR4veEXuwCC2wARtG.jpg', 'release_date': '1995-10-30', 'runtime':

#### **Apply Filter**

In [ ]:
!pip install pafy
!pip install youtube_dl

     |████████████████████████████████| 1.9MB 5.6MB/s 


In [ ]:
!pip install tensorflow==1.13.1
!pip install keras==2.3.0

     |████████████████████████████████| 92.6MB 100kB/s 
     |████████████████████████████████| 3.2MB 36.0MB/s 
     |████████████████████████████████| 51kB 6.0MB/s 
     |████████████████████████████████| 368kB 25.0MB/s 
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1
     |████████████████████████████████| 378kB 4.2MB/s 
  Found existing installation: Keras 2.4.3
    Uninstalling Keras-2.4.3:
      Successfully uninstalled Keras-2.4.3


In [ ]:
import pafy
import cv2
import ast

In [ ]:
def genres_filter(data,genres):
  genres_list = ast.literal_eval(data['Video Info']['genres'])
  found = False
  for each in genres_list:
    if each['name'] == genres:
      found = True
      print('Genres Match')
      break;   
  return found

In [ ]:
def length_filter(video_streams,length):
  fps = video_streams.get(cv2.CAP_PROP_FPS) 
  frame_count = int(video_streams.get(cv2.CAP_PROP_FRAME_COUNT))
  video_length = frame_count/fps
  print('Duration: {} sec '.format(video_length) )
  return True if video_length<length else False

In [ ]:
def get_video_data(num_videos, length,genres,video_list):

  video_list_copy = dict(video_list)
  n = 0
  for i,(key, value) in enumerate(video_list_copy.items()):
      print('------------------ ID {} ------------------'.format(key))
      streams = [];

      #Filter: Genres
      if genres  != 'NA':
        temp = genres_filter(value,genres)
        if (temp == False): 
          continue
      for eachVideo in value['Youtube Info']:
        url = eachVideo[1]
        try:
          n+=1
          youtube_video = pafy.new(url)
          youtube_video = youtube_video.getbest()
          video_streams = cv2.VideoCapture(youtube_video.url)
          #Filter: Video Length
          if (length_filter(video_streams,length)):
            print('Within Limit')
            streams.append([eachVideo[0],eachVideo[1],video_streams])
        except:
          print('Pafy Get Wrong')
        
        if n != 0 and n % 20 == 0:
            print('===================== Sleep =====================')
            time.sleep(10)

      video_list_copy[key]['Youtube Info'] = streams
      if i>=num_videos:
        break;
  
  return video_list_copy


In [ ]:
num_videos=10
length = 120 #max length , sec
genres = 'Comedy'
video_data_stream = get_video_data(num_videos,length,genres,test_trailer_list)

------------------ ID 862 ------------------
Genres Match
Duration: 89.65623333333333 sec 
Within Limit
Duration: 88.04628888888888 sec 
Within Limit
Duration: 187.10357777777776 sec 
------------------ ID 8844 ------------------
------------------ ID 15602 ------------------
Genres Match
Duration: 111.8117 sec 
Within Limit
------------------ ID 31357 ------------------
Genres Match
Pafy Get Wrong
------------------ ID 11862 ------------------
Genres Match
Duration: 155.6555 sec 
------------------ ID 949 ------------------
------------------ ID 11860 ------------------
Genres Match
Pafy Get Wrong
Duration: 174.50766666666667 sec 
------------------ ID 45325 ------------------
------------------ ID 9091 ------------------
------------------ ID 710 ------------------
------------------ ID 9087 ------------------
Genres Match
Duration: 169.169 sec 


In [ ]:
#Demo
for key, value in test_trailer_list.items():
  for each in value:

    url = each[1]
    try:
      vPafy = pafy.new(url)
      play = vPafy.getbest()
      video_streams = cv2.VideoCapture(play.url)
      
      fps = video_streams.get(cv2.CAP_PROP_FPS) 
      frame_count = int(video_streams.get(cv2.CAP_PROP_FRAME_COUNT))
      duration = frame_count/fps
      print('Video Title : {} ------- Duration: {} sec '.format(each[0],duration) )
    except:
      print('Pafy Get Wrong')


Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get Wrong
Pafy Get W

**Pafy concern, something might went wrong at here**

# Object Detection Preparing For Information Organization Part

**Intro to Pafy:**

https://pythonhosted.org/pafy/

##**information from object detection **

In [ ]:
pip install tensorflow==2.4.0

     |████████████████████████████████| 394.7MB 44kB/s 
     |████████████████████████████████| 10.6MB 48.6MB/s 
     |████████████████████████████████| 471kB 42.9MB/s 
  Found existing installation: tensorboard 1.13.1
    Uninstalling tensorboard-1.13.1:
      Successfully uninstalled tensorboard-1.13.1
  Found existing installation: tensorflow-estimator 1.13.0
    Uninstalling tensorflow-estimator-1.13.0:
      Successfully uninstalled tensorflow-estimator-1.13.0
  Found existing installation: tensorflow 1.13.1
    Uninstalling tensorflow-1.13.1:
      Successfully uninstalled tensorflow-1.13.1


In [ ]:
pip install tensorflow-gpu==2.4.0

     |████████████████████████████████| 394.7MB 42kB/s 


In [ ]:
pip install keras==2.4.3 numpy==1.19.3 pillow==7.0.0 scipy==1.4.1 h5py==2.10.0 matplotlib==3.3.2 opencv-python keras-resnet==0.2.0

     |████████████████████████████████| 14.9MB 340kB/s 
     |████████████████████████████████| 11.6MB 47.9MB/s 
  Created wheel for keras-resnet: filename=keras_resnet-0.2.0-py2.py3-none-any.whl size=20486 sha256=5220f2fc2c35c10050b744a90f1264fbac89874f77f5f69dd28a835268494c05
  Stored in directory: /root/.cache/pip/wheels/5f/09/a5/497a30fd9ad9964e98a1254d1e164bcd1b8a5eda36197ecb3c
Successfully built keras-resnet
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Found existing installation: Keras 2.3.0
    Uninstalling Keras-2.3.0:
      Successfully uninstalled Keras-2.3.0
  Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matpl

**install ImageAi**

In [ ]:
pip install imageai --upgrade

     |████████████████████████████████| 163kB 3.5MB/s 


In [ ]:
!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/resnet50_coco_best_v2.0.1.h5

--2021-02-24 03:15:43--  https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/resnet50_coco_best_v2.0.1.h5
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-releases.githubusercontent.com/125932201/e7ab678c-6146-11e8-85cc-26bc1cd06ab0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210224%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210224T031543Z&X-Amz-Expires=300&X-Amz-Signature=e03f032119dc56ced98b4c6963763c271bc17c4ac7e8649c126bd18ed08658df&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=125932201&response-content-disposition=attachment%3B%20filename%3Dresnet50_coco_best_v2.0.1.h5&response-content-type=application%2Foctet-stream [following]
--2021-02-24 03:15:43--  https://github-releases.githubusercontent.com/125932201/e7ab678c-6146-11e8-85cc-26bc1cd06ab0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Cre

In [ ]:
!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo.h5

--2021-02-24 03:15:47--  https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo.h5
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-releases.githubusercontent.com/125932201/1b8496e8-86fc-11e8-895f-fefe61ebb499?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210224%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210224T031547Z&X-Amz-Expires=300&X-Amz-Signature=cc70463cfe20422aff11f40a7c4bf1221ea2ab0f1457a3893f4bdca926557bfd&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=125932201&response-content-disposition=attachment%3B%20filename%3Dyolo.h5&response-content-type=application%2Foctet-stream [following]
--2021-02-24 03:15:47--  https://github-releases.githubusercontent.com/125932201/1b8496e8-86fc-11e8-895f-fefe61ebb499?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210224%2F

In [ ]:
!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo-tiny.h5

--2021-02-24 03:15:51--  https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo-tiny.h5
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-releases.githubusercontent.com/125932201/7cf559e6-86fa-11e8-81e8-1e959be261a8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210224%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210224T031551Z&X-Amz-Expires=300&X-Amz-Signature=0fad4cc019df55f9ab943a011e3985919f7cfc1e46582a0fa6aa29575b48c279&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=125932201&response-content-disposition=attachment%3B%20filename%3Dyolo-tiny.h5&response-content-type=application%2Foctet-stream [following]
--2021-02-24 03:15:51--  https://github-releases.githubusercontent.com/125932201/7cf559e6-86fa-11e8-81e8-1e959be261a8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F2

In [ ]:

import pafy

In [ ]:
from imageai.Detection import VideoObjectDetection
import matplotlib as plt
import numpy as np
import os
import time
import cv2

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
execution_path = os.getcwd()

detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
detector.loadModel()

In [ ]:
def forSeconds_modified(second_number, output_arrays, count_arrays, average_output_count):
    print("SECOND : ", second_number)
    print("Array for the outputs of each frame ", output_arrays)
    print("Array for output count for unique objects in each frame : ", count_arrays)
    print("Output average count for unique objects in the last second: ", average_output_count)
    #output_Collection.append((second_number,output_arrays,count_arrays,average_output_count))
    output_second_output_array.append((second_number, output_arrays))
    print("------------END OF A SECOND --------------")

In [ ]:
def detect_objects_url(input_detector,url,fileName,logProgress = True,frames_per_second = 10):

  file_path_out = '/content/gdrive/My Drive/Capstone/Code/test output/' + fileName +'_outDetect'

  #Get Video info from youtube
  vPafy = pafy.new(url)
  play = vPafy.getbest()

  #Video to Video Streams
  video_streams = cv2.VideoCapture(play.url)
  frames_per_second = video_streams.get(cv2.CAP_PROP_FPS)
  print('frames_per_second = ',frames_per_second)
  frames_per_second = int(frames_per_second)
  print('frames_per_second 2= ',frames_per_second)


  #start: object detection
  start_time = time.time()
  video_path= input_detector.detectObjectsFromVideo(
                                camera_input=video_streams,
                                output_file_path=file_path_out,  #save output video
                                frames_per_second=frames_per_second, 
                                per_second_function=forSeconds_modified,
                                log_progress=logProgress,
                                minimum_percentage_probability=70)
  
  end_time = time.time()
  elapsed_time = end_time - start_time

  return video_path, elapsed_time

**Youtube videos that can be used:**
1. 1sec video, has only cat 'https://www.youtube.com/watch?v=tPEE9ZwTmy0'
2. 38 sec video, https://www.youtube.com/watch?v=4nOSvpnCFTs
3. 10 sec animal video https://www.youtube.com/watch?v=wGyUP4AlZ6I

In [ ]:
#YOLOv3
output_second_output_array = []
f_name = 'Test_vToUrl_2'
url = 'https://www.youtube.com/watch?v=wGyUP4AlZ6I'
logProgress=False
frames_per_second = 10
video_path_1,elapsed_time_1  = detect_objects_url(detector,url = url,fileName = f_name,logProgress=logProgress,frames_per_second = frames_per_second)
output_Collection_1 = output_second_output_array

frames_per_second =  29.97002997002997
frames_per_second 2=  29
SECOND :  1
Array for the outputs of each frame  [[{'name': 'cat', 'percentage_probability': 99.76495504379272, 'box_points': [46, 109, 310, 360]}], [{'name': 'cat', 'percentage_probability': 99.76335763931274, 'box_points': [45, 109, 310, 360]}], [{'name': 'cat', 'percentage_probability': 93.91093850135803, 'box_points': [38, 113, 312, 367]}], [{'name': 'cat', 'percentage_probability': 92.661052942276, 'box_points': [38, 113, 312, 367]}], [{'name': 'cat', 'percentage_probability': 97.72024750709534, 'box_points': [39, 98, 308, 373]}], [{'name': 'cat', 'percentage_probability': 99.81682300567627, 'box_points': [34, 94, 298, 369]}], [{'name': 'cat', 'percentage_probability': 99.75711703300476, 'box_points': [32, 83, 302, 372]}], [{'name': 'cat', 'percentage_probability': 99.40569996833801, 'box_points': [40, 85, 310, 370]}], [{'name': 'cat', 'percentage_probability': 99.46343898773193, 'box_points': [39, 82, 312, 370]}], [{

Analysis on the **output_Collection_1**, **output_Collection_1** is an arrary type. Here are some more detailed information about this array. 

1. output_Collection[0] contains all detected boxes within one second frame 
2. output_Collection_1[3][0] is the number of the second 



In [ ]:
output_Collection_1

[(1,
  [[{'box_points': [46, 109, 310, 360],
     'name': 'cat',
     'percentage_probability': 99.76495504379272}],
   [{'box_points': [45, 109, 310, 360],
     'name': 'cat',
     'percentage_probability': 99.76335763931274}],
   [{'box_points': [38, 113, 312, 367],
     'name': 'cat',
     'percentage_probability': 93.91093850135803}],
   [{'box_points': [38, 113, 312, 367],
     'name': 'cat',
     'percentage_probability': 92.661052942276}],
   [{'box_points': [39, 98, 308, 373],
     'name': 'cat',
     'percentage_probability': 97.72024750709534}],
   [{'box_points': [34, 94, 298, 369],
     'name': 'cat',
     'percentage_probability': 99.81682300567627}],
   [{'box_points': [32, 83, 302, 372],
     'name': 'cat',
     'percentage_probability': 99.75711703300476}],
   [{'box_points': [40, 85, 310, 370],
     'name': 'cat',
     'percentage_probability': 99.40569996833801}],
   [{'box_points': [39, 82, 312, 370],
     'name': 'cat',
     'percentage_probability': 99.463438987731

In [ ]:
output_Collection_1[3]

(4,
 [[{'box_points': [161, 32, 337, 351],
    'name': 'cat',
    'percentage_probability': 99.89566206932068}],
  [{'box_points': [21, 22, 342, 375],
    'name': 'dog',
    'percentage_probability': 85.55852770805359}],
  [{'box_points': [32, 37, 331, 364],
    'name': 'cat',
    'percentage_probability': 84.17324423789978}],
  [{'box_points': [35, 38, 326, 364],
    'name': 'cat',
    'percentage_probability': 74.5589554309845}],
  [],
  [{'box_points': [46, 66, 354, 371],
    'name': 'dog',
    'percentage_probability': 74.6390163898468}],
  [{'box_points': [46, 65, 353, 374],
    'name': 'dog',
    'percentage_probability': 77.89881229400635}],
  [{'box_points': [30, 74, 313, 338],
    'name': 'cat',
    'percentage_probability': 96.5566873550415}],
  [{'box_points': [40, 78, 313, 354],
    'name': 'cat',
    'percentage_probability': 96.52072191238403}],
  [{'box_points': [51, 79, 312, 356],
    'name': 'cat',
    'percentage_probability': 96.58342599868774}],
  [{'box_points': [6

In [ ]:
len(output_Collection_1[2])

2

In [ ]:
output_Collection_1[3][1]

[[{'box_points': [161, 32, 337, 351],
   'name': 'cat',
   'percentage_probability': 99.89566206932068}],
 [{'box_points': [21, 22, 342, 375],
   'name': 'dog',
   'percentage_probability': 85.55852770805359}],
 [{'box_points': [32, 37, 331, 364],
   'name': 'cat',
   'percentage_probability': 84.17324423789978}],
 [{'box_points': [35, 38, 326, 364],
   'name': 'cat',
   'percentage_probability': 74.5589554309845}],
 [],
 [{'box_points': [46, 66, 354, 371],
   'name': 'dog',
   'percentage_probability': 74.6390163898468}],
 [{'box_points': [46, 65, 353, 374],
   'name': 'dog',
   'percentage_probability': 77.89881229400635}],
 [{'box_points': [30, 74, 313, 338],
   'name': 'cat',
   'percentage_probability': 96.5566873550415}],
 [{'box_points': [40, 78, 313, 354],
   'name': 'cat',
   'percentage_probability': 96.52072191238403}],
 [{'box_points': [51, 79, 312, 356],
   'name': 'cat',
   'percentage_probability': 96.58342599868774}],
 [{'box_points': [67, 77, 344, 340],
   'name': 'cat

In [ ]:
output_Collection_1[3][1][23][0]

{'box_points': [277, 29, 461, 150],
 'name': 'chair',
 'percentage_probability': 75.08959770202637}

In [ ]:
output_Collection_1[5][1][25]

[{'box_points': [1, 89, 346, 364],
  'name': 'cat',
  'percentage_probability': 99.88466501235962},
 {'box_points': [25, 91, 466, 377],
  'name': 'bed',
  'percentage_probability': 72.27616906166077}]

In [ ]:
output_Collection_1[0][1][4][0]['box_points']

[39, 98, 308, 373]

In [ ]:
output_Collection_1[0][1][4][0]

{'box_points': [39, 98, 308, 373],
 'name': 'cat',
 'percentage_probability': 97.72024750709534}

output_Collection_1[]

In [ ]:
elapsed_time_1

1478.117753982544

In [ ]:
np.save('output_Collection_1', output_Collection_1)

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


### **Process object infomation**


Current Logic: 


*   For each frame: 
  * **Choose object with probality > 70%**
      * Note: ImageAI has accuracy filter
  * **Count occurrences of each object type** , select the **Main object**
  * Multiple Main object: **Calculate area of the each Main object**, choose the largest. 
*  For each second:
    * Choose object that last **longer than 2 second**



# **Cases Analysis:**
Main purpose of the function is to limit the detected objects 

1.   Multiple same type objects --> Output the one closer to the center.
2.   Filter out the ones with lower probability --> Accuracy above 85%.
3.   Mislabelling --> Object Tracking, limited the ones under a period of time.
4.   Filtering out the ones that are occupying small area on the screen. 


In [ ]:
from collections import Counter

In [ ]:
def calc_area(box_point):
  x1,y1,x2,y2 = box_point
  area = (x2-x1) * (y2-y1)
  return area

In [ ]:
def find_box_middle(box_point):
  x1,y1,x2,y2 = box_point
  x_middle = (x1 + x2)/2
  y_middle = (y1 + y2)/2
  middle_point = [x_middle, y_middle]
  return middle_point

In [ ]:
output_Collection_1

[(1,
  [[{'box_points': [46, 109, 310, 360],
     'name': 'cat',
     'percentage_probability': 99.76495504379272}],
   [{'box_points': [45, 109, 310, 360],
     'name': 'cat',
     'percentage_probability': 99.76335763931274}],
   [{'box_points': [38, 113, 312, 367],
     'name': 'cat',
     'percentage_probability': 93.91093850135803}],
   [{'box_points': [38, 113, 312, 367],
     'name': 'cat',
     'percentage_probability': 92.661052942276}],
   [{'box_points': [39, 98, 308, 373],
     'name': 'cat',
     'percentage_probability': 97.72024750709534}],
   [{'box_points': [34, 94, 298, 369],
     'name': 'cat',
     'percentage_probability': 99.81682300567627}],
   [{'box_points': [32, 83, 302, 372],
     'name': 'cat',
     'percentage_probability': 99.75711703300476}],
   [{'box_points': [40, 85, 310, 370],
     'name': 'cat',
     'percentage_probability': 99.40569996833801}],
   [{'box_points': [39, 82, 312, 370],
     'name': 'cat',
     'percentage_probability': 99.463438987731

# Analysis on the array output 


Output array is organized in a way so that, the output was in the format second by second and within each second, objects detected in each frame were further be packed into multiple arrays. 

```
output_array = [second1[frame1[object1{},object2{},object3{}],frame2[object1{},object2{},object3{},object4{}],frame3[object1{},object2{},object3{}],frame4[object1{},object2{},object3{}],frame5[object1{},object2{},object3{}]]]
```


```
{'name': 'cat', 'percentage_probability': 99.76495504379272, 'box_points': [46, 109, 310, 360]}
```




processing it based on the theories below:
# **Cases Analysis:**
Main purpose of the function is to limit the detected objects 

1.   Multiple same type objects --> Output the one closer to the center.
2.   Filter out the ones with lower probability --> Accuracy above 85%.
3.   Mislabelling --> Object Tracking, limited the ones under a period of time.
4.   Filtering out the ones that are occupying small area on the screen. 



In [ ]:
# assuming box_array being in the format as below
# pass in the info array --> output_Collection_1
# will reformat it with sec and frame number attached
def reformat_ouput(output_info_collection):
  output_frame_array = []
  frame_second = []
  
  for i in range(len(output_info_collection)): # i number of seconds in total
    print("^^^^^^^^^^^^^^^start^^^^^^^^^^^^^^^^^^")
    print("second number is: ", output_info_collection[i][0])
    
    for j in range(len(output_info_collection[i][1])): # number of frames 
      
      print('The number of frames is: {}'.format(len(output_info_collection[i][1])))
      print("============================")
      print('This correspond to the {0} second {1} frame'.format(i,j))
      print(output_info_collection[i][1][j])
      #directly choose the first output object detected within the frame
      
      if(len(output_info_collection[i][1][j])!=0):
        print('This correspond to the {0} second {1} frame, type is: {2}, with accuracy {4}, location: {3}'.format(i,j,output_info_collection[i][1][j][0]['name'],output_info_collection[i][1][j][0]['box_points'],output_info_collection[i][1][j][0]['percentage_probability']))
        object_area = calc_area(output_info_collection[i][1][j][0]['box_points'])
        box_central = find_box_middle(output_info_collection[i][1][j][0]['box_points'])      
        print('the area of the detected object {0}, the central location of the object {1}'.format(object_area, box_central))
        object_type = output_info_collection[i][1][j][0]['name'] 
        print("object type is: ", object_type)
        print("****************************")
        frame_info = {'second': i, 'frame': j, 'type':output_info_collection[i][1][j][0]['name'], 'accuracy':output_info_collection[i][1][j][0]['percentage_probability'], 'location': output_info_collection[i][1][j][0]['box_points'], 'area': object_area, 'central location': box_central}

        output_frame_array.append(frame_info)
      frame_second.append([output_info_collection[i][0],frame_info])
      
  return output_frame_array, frame_second


In [ ]:
output_dic_reformated, reformat_frame_second = reformat_ouput(output_Collection_1)

^^^^^^^^^^^^^^^start^^^^^^^^^^^^^^^^^^
second number is:  1
The number of frames is: 29
This correspond to the 0 second 0 frame
[{'name': 'cat', 'percentage_probability': 99.76495504379272, 'box_points': [46, 109, 310, 360]}]
This correspond to the 0 second 0 frame, type is: cat, with accuracy 99.76495504379272, location: [46, 109, 310, 360]
the area of the detected object 66264, the central location of the object [178.0, 234.5]
object type is:  cat
****************************
The number of frames is: 29
This correspond to the 0 second 1 frame
[{'name': 'cat', 'percentage_probability': 99.76335763931274, 'box_points': [45, 109, 310, 360]}]
This correspond to the 0 second 1 frame, type is: cat, with accuracy 99.76335763931274, location: [45, 109, 310, 360]
the area of the detected object 66515, the central location of the object [177.5, 234.5]
object type is:  cat
****************************
The number of frames is: 29
This correspond to the 0 second 2 frame
[{'name': 'cat', 'percenta

In [ ]:
print(reformat_frame_second[46])


[2, {'second': 1, 'frame': 17, 'type': 'cat', 'accuracy': 99.33972358703613, 'location': [11, 63, 309, 366], 'area': 90294, 'central location': [160.0, 214.5]}]


In [ ]:

len(reformat_frame_second)

232

In [ ]:
print(output_dic_reformated)

[{'second': 0, 'frame': 0, 'type': 'cat', 'accuracy': 99.76495504379272, 'location': [46, 109, 310, 360], 'area': 66264, 'central location': [178.0, 234.5]}, {'second': 0, 'frame': 1, 'type': 'cat', 'accuracy': 99.76335763931274, 'location': [45, 109, 310, 360], 'area': 66515, 'central location': [177.5, 234.5]}, {'second': 0, 'frame': 2, 'type': 'cat', 'accuracy': 93.91093850135803, 'location': [38, 113, 312, 367], 'area': 69596, 'central location': [175.0, 240.0]}, {'second': 0, 'frame': 3, 'type': 'cat', 'accuracy': 92.661052942276, 'location': [38, 113, 312, 367], 'area': 69596, 'central location': [175.0, 240.0]}, {'second': 0, 'frame': 4, 'type': 'cat', 'accuracy': 97.72024750709534, 'location': [39, 98, 308, 373], 'area': 73975, 'central location': [173.5, 235.5]}, {'second': 0, 'frame': 5, 'type': 'cat', 'accuracy': 99.81682300567627, 'location': [34, 94, 298, 369], 'area': 72600, 'central location': [166.0, 231.5]}, {'second': 0, 'frame': 6, 'type': 'cat', 'accuracy': 99.75711

In [ ]:
len(output_dic_reformated)

200

In [ ]:
output_dic_reformated[10]

{'accuracy': 99.73866939544678,
 'area': 75600,
 'central location': [172.0, 226.0],
 'frame': 10,
 'location': [32, 91, 312, 361],
 'second': 0,
 'type': 'cat'}

In [ ]:
output_dic_reformated

[{'accuracy': 99.76495504379272,
  'area': 66264,
  'central location': [178.0, 234.5],
  'frame': 0,
  'location': [46, 109, 310, 360],
  'second': 0,
  'type': 'cat'},
 {'accuracy': 99.76335763931274,
  'area': 66515,
  'central location': [177.5, 234.5],
  'frame': 1,
  'location': [45, 109, 310, 360],
  'second': 0,
  'type': 'cat'},
 {'accuracy': 93.91093850135803,
  'area': 69596,
  'central location': [175.0, 240.0],
  'frame': 2,
  'location': [38, 113, 312, 367],
  'second': 0,
  'type': 'cat'},
 {'accuracy': 92.661052942276,
  'area': 69596,
  'central location': [175.0, 240.0],
  'frame': 3,
  'location': [38, 113, 312, 367],
  'second': 0,
  'type': 'cat'},
 {'accuracy': 97.72024750709534,
  'area': 73975,
  'central location': [173.5, 235.5],
  'frame': 4,
  'location': [39, 98, 308, 373],
  'second': 0,
  'type': 'cat'},
 {'accuracy': 99.81682300567627,
  'area': 72600,
  'central location': [166.0, 231.5],
  'frame': 5,
  'location': [34, 94, 298, 369],
  'second': 0,
  

In [ ]:
def object_occurrence_within_second_frame(output_dic_reformated):
  format_output_info_array = []
  count = 1
  for i in range(len(output_dic_reformated)-1):
    
    print("===============")
    print("Inside the loop")
    print("Numbers in the range:", i)
    if ((output_dic_reformated[i]['second'] == output_dic_reformated[i+1]['second']) and (output_dic_reformated[i]['type'] == output_dic_reformated[i+1]['type'])):
      count += 1
    elif ((output_dic_reformated[i]['second'] != output_dic_reformated[i+1]['second']) or (output_dic_reformated[i]['type'] != output_dic_reformated[i+1]['type'])):
      print("*********************************")
      print("ready for restart!!")
      print("count before restart is: ", count)
      print("continues counting on the object is: ", output_dic_reformated[i]['type'])
      print("we are currently on the {} second".format(output_dic_reformated[i]['second']))
      insert_frame = {'object_type': output_dic_reformated[i]['type'], 'current_second': output_dic_reformated[i]['second'], 'frame_count': count}
      format_output_info_array.append(insert_frame)
      count = 1

  print("**************************************")    
  print("count after restart is: ", count)
  print("last continuous occurred object is: ", output_dic_reformated[i+1]['type'])
  print("we are currently on the {} second".format(output_dic_reformated[i+1]['second']))
  insert_frame = {'object_type': output_dic_reformated[i+1]['type'], 'current_second': output_dic_reformated[i+1]['second'], 'frame_count': count}
  format_output_info_array.append(insert_frame)

  return format_output_info_array

In [ ]:
processed_array = object_occurrence_within_second_frame(output_dic_reformated)

Inside the loop
Numbers in the range: 0
Inside the loop
Numbers in the range: 1
Inside the loop
Numbers in the range: 2
Inside the loop
Numbers in the range: 3
Inside the loop
Numbers in the range: 4
Inside the loop
Numbers in the range: 5
Inside the loop
Numbers in the range: 6
Inside the loop
Numbers in the range: 7
Inside the loop
Numbers in the range: 8
Inside the loop
Numbers in the range: 9
Inside the loop
Numbers in the range: 10
Inside the loop
Numbers in the range: 11
Inside the loop
Numbers in the range: 12
Inside the loop
Numbers in the range: 13
Inside the loop
Numbers in the range: 14
Inside the loop
Numbers in the range: 15
Inside the loop
Numbers in the range: 16
Inside the loop
Numbers in the range: 17
Inside the loop
Numbers in the range: 18
Inside the loop
Numbers in the range: 19
Inside the loop
Numbers in the range: 20
Inside the loop
Numbers in the range: 21
Inside the loop
Numbers in the range: 22
Inside the loop
Numbers in the range: 23
Inside the loop
Numbers in

In [ ]:
def final_intent_reformat(pro_arrayInFrames):
  output_info_dictionary = {}

  for i in range(len(pro_arrayInFrames)):
    print("the iteration number we are entering is: ", i)
    #checking if type already exist in the output dictionary
    typeCheck = pro_arrayInFrames[i]['object_type']
    
    if typeCheck in output_info_dictionary :
      #update second number if already exist in the dictionary 
      sec_num = pro_arrayInFrames[i]['current_second']
      value_list = output_info_dictionary[typeCheck]
      if sec_num not in value_list:
        output_info_dictionary[typeCheck].append(sec_num)
    # has not occurred before, create a new position for it
    else:
      d = {}
      d[typeCheck] = []
      sec_num = pro_arrayInFrames[i]['current_second']
      d[typeCheck].append(sec_num)
      output_info_dictionary.update(d)

  return output_info_dictionary
  

In [ ]:
final_dic_output = final_intent_reformat(processed_array)

the iteration number we are entering is:  0
the iteration number we are entering is:  1
the iteration number we are entering is:  2
the iteration number we are entering is:  3
the iteration number we are entering is:  4
the iteration number we are entering is:  5
the iteration number we are entering is:  6
the iteration number we are entering is:  7
the iteration number we are entering is:  8
the iteration number we are entering is:  9
the iteration number we are entering is:  10
the iteration number we are entering is:  11
the iteration number we are entering is:  12
the iteration number we are entering is:  13
the iteration number we are entering is:  14
the iteration number we are entering is:  15
the iteration number we are entering is:  16
the iteration number we are entering is:  17
the iteration number we are entering is:  18
the iteration number we are entering is:  19
the iteration number we are entering is:  20
the iteration number we are entering is:  21


In [ ]:
final_dic_output

{'cat': [0, 1, 2, 3, 4, 5, 6],
 'chair': [3],
 'dog': [1, 3, 4, 6, 7],
 'person': [1]}

In [ ]:
processed_array

[{'current_second': 0, 'frame_count': 29, 'object_type': 'cat'},
 {'current_second': 1, 'frame_count': 19, 'object_type': 'cat'},
 {'current_second': 1, 'frame_count': 4, 'object_type': 'person'},
 {'current_second': 1, 'frame_count': 1, 'object_type': 'dog'},
 {'current_second': 1, 'frame_count': 3, 'object_type': 'person'},
 {'current_second': 2, 'frame_count': 26, 'object_type': 'cat'},
 {'current_second': 3, 'frame_count': 1, 'object_type': 'cat'},
 {'current_second': 3, 'frame_count': 1, 'object_type': 'dog'},
 {'current_second': 3, 'frame_count': 2, 'object_type': 'cat'},
 {'current_second': 3, 'frame_count': 2, 'object_type': 'dog'},
 {'current_second': 3, 'frame_count': 7, 'object_type': 'cat'},
 {'current_second': 3, 'frame_count': 7, 'object_type': 'chair'},
 {'current_second': 3, 'frame_count': 1, 'object_type': 'cat'},
 {'current_second': 3, 'frame_count': 3, 'object_type': 'chair'},
 {'current_second': 3, 'frame_count': 3, 'object_type': 'dog'},
 {'current_second': 3, 'fra

In [78]:
def final_intent_reformat_update(pro_arrayInFrames):
  output_info_dictionary = {}

  for i in range(len(pro_arrayInFrames)):
    print("the iteration number we are entering is: ", i)
    #checking if type already exist in the output dictionary
    typeCheck = pro_arrayInFrames[i]['object_type']
    
    if typeCheck in output_info_dictionary :
      print("this type has occured before, which is: ", typeCheck)
      #update second number if already exist in the dictionary 
      sec_num = pro_arrayInFrames[i]['current_second']
      value_list = output_info_dictionary[typeCheck]
      last_sec = value_list[-1][1]
      print("current value list is: ", value_list)
      print("seems like the last sec is: ", last_sec)
      #checking if last element needs to be updated or not 
      #value_list[-1][1]
      if ((last_sec+1) == sec_num) :#needs to be updated to the newest
        value_list[-1][1] = sec_num
        print("value list after updating is: ",value_list )
      elif (last_sec != sec_num): #second number is not continuous 
        sec_inner_arr = [sec_num,sec_num]
        value_list.append(sec_inner_arr)

    # has not occurred before, create a new position for it
    else:
      print("this type has not occured before, which is: ", typeCheck)
      d = {}
      d[typeCheck] = []
      sec_num = pro_arrayInFrames[i]['current_second']
      sec_inner_arr = [sec_num,sec_num]
      d[typeCheck].append(sec_inner_arr)
      output_info_dictionary.update(d)

  return output_info_dictionary
  

In [79]:
updated_arry = final_intent_reformat_update(processed_array)

the iteration number we are entering is:  0
this type has not occured before, which is:  cat
the iteration number we are entering is:  1
this type has occured before, which is:  cat
current value list is:  [[0, 0]]
seems like the last sec is:  0
value list after updating is:  [[0, 1]]
the iteration number we are entering is:  2
this type has not occured before, which is:  person
the iteration number we are entering is:  3
this type has not occured before, which is:  dog
the iteration number we are entering is:  4
this type has occured before, which is:  person
current value list is:  [[1, 1]]
seems like the last sec is:  1
the iteration number we are entering is:  5
this type has occured before, which is:  cat
current value list is:  [[0, 1]]
seems like the last sec is:  1
value list after updating is:  [[0, 2]]
the iteration number we are entering is:  6
this type has occured before, which is:  cat
current value list is:  [[0, 2]]
seems like the last sec is:  2
value list after updati

In [80]:
updated_arry

{'cat': [[0, 6]],
 'chair': [[3, 3]],
 'dog': [[1, 1], [3, 4], [6, 7]],
 'person': [[1, 1]]}

In [86]:
for x in updated_arry.values():
  print("x values in the dictionary is: ", x)
  print("the length of the values in the dictionary is: ", len(x))

x values in the dictionary is:  [[0, 6]]
the length of the values in the dictionary is:  1
x values in the dictionary is:  [[1, 1]]
the length of the values in the dictionary is:  1
x values in the dictionary is:  [[1, 1], [3, 4], [6, 7]]
the length of the values in the dictionary is:  3
x values in the dictionary is:  [[3, 3]]
the length of the values in the dictionary is:  1


In [104]:
def quality_score_attempt_version2(updated_arry):
  score_arry = []
  attempt_score = 10
  for x in updated_arry:
    type_score = 0
    print("current x value is: ", x)
    print("the length of the value is: ", len(updated_arry[x]))
    num_arr = len(updated_arry[x])
    for i in range(num_arr):
      type_score = type_score + updated_arry[x][i][1] - updated_arry[x][i][0] + attempt_score
    print("attemp score is: ", type_score)
    output_dict = {x: updated_arry[x], 'score': type_score}
    score_arry.append(output_dict)
  return score_arry

In [105]:
update_arr = quality_score_attempt_version2(updated_arry)

current x value is:  cat
the length of the value is:  1
attemp score is:  16
current x value is:  person
the length of the value is:  1
attemp score is:  10
current x value is:  dog
the length of the value is:  3
attemp score is:  32
current x value is:  chair
the length of the value is:  1
attemp score is:  10


In [106]:
update_arr

[{'cat': [[0, 6]], 'score': 16},
 {'person': [[1, 1]], 'score': 10},
 {'dog': [[1, 1], [3, 4], [6, 7]], 'score': 32},
 {'chair': [[3, 3]], 'score': 10}]

{'cat': [0,6][8],
 'chair': [3],
 'dog': [1],[3],[6,8],
 'elephant': [8],
 'person': [1]}

In [ ]:
def quality_score_attempt(output_dictionay):
  score_arry = []
  #this number could be modified
  attempt_score = 10
  for x in output_dictionay:
    print("current x value is: ", x)
    print("the length of the value is: ", len(output_dictionay[x]))
    second_num = len(output_dictionay[x])
    final_score = attempt_score * second_num
    print("final attempted score is: ", final_score)
    output_dict = {x: output_dictionay[x], 'score': final_score}
    score_arry.append(output_dict)
  return score_arry


In [ ]:
score_array = quality_score_attempt(final_dic_output)

In [ ]:
score_array

In [ ]:
[{'cat': [0, 1, 2, 3, 4, 5, 6, 8], 'score': 30},
 {'person': [1], 'score': 60},
 {'dog': [1, 3, 6, 7, 8], 'score': 30},
 {'chair': [3], 'score': 50},
 {'elephant': [8], 'score': 80}]

# **Quality Score **

# code graveyard 


In [ ]:
final_dic_output['cat']

In [ ]:
len(final_dic_output)

In [ ]:
for x in final_dic_output.values():
  print(len(x))

In [ ]:
processed_array[4]

In [ ]:
for i in range(len(processed_array)):
  print(i)

print(i+1)

In [ ]:
count = 1
for i in range(len(output_dic_reformated)-1):
  
  print("===============")
  print("Inside the loop")
  print("Numbers in the range:", i)
  if ((output_dic_reformated[i]['second'] == output_dic_reformated[i+1]['second']) and 
      (output_dic_reformated[i]['type'] == output_dic_reformated[i+1]['type'])):
    count += 1
  elif ((output_dic_reformated[i]['second'] != output_dic_reformated[i+1]['second']) or
        (output_dic_reformated[i]['type'] != output_dic_reformated[i+1]['type'])):
    print("ready for restart!!")
    print("same object occured in {0} times upto the {1} second".format(count,output_dic_reformated[i+1]['second']))
    print("object is: ",output_dic_reformated[i+1]['type'])
    count = 1
    
print("same object occured in {0} times upto the {1} second".format(count,output_dic_reformated[i+1]['second']))
print("object is: ",output_dic_reformated[i+1]['type'])

In [ ]:
# assuming box_array being in the format as below
# pass in the info array --> output_Collection_1
# will reformat it with sec and frame number attached
def reformat_ouput(output_info_collection):
  output_info_array = dict()

  for i in range(len(output_info_collection)): # i number of seconds in total
    print(i) 
    for j in range(len(output_info_collection[i][1])): # j is the total number of boxes
      print(j)
      print(output_info_collection[i][1])
      for k in range(len(output_info_collection[i][1][j])):# k is box number within a frame
        print(k)
        print(output_info_collection[i][1][j])
        box_location = output_info_collection[i][1][j][0]['box_points']
        print(box_location)
        box_location_central = find_box_middle(box_location)
        print(box_location_central)
        collect = {"second_number: {}".format(i): box_location_central}
        output_info_array.update(collect)

  return output_info_array
  
#########untested#######